export const SAVE_PERSONAL_DATA = "SAVE_PERSONAL_DATA"
export const SAVE_ADDRESS_DATA = "SAVE_ADDRESS_DATA"

export const FETCH_MEMBERS_DATA_ERROR = "FETCH_MEMBERS_DATA_ERROR"
export const FETCH_MEMBERS_DATA = "FETCH_MEMBERS_DATA"