export const GET_APPLICANTS_SUCCESS = "GET_APPLICANTS_SUCCESS";
export const GET_APPLICANTS_FAILURE = "GET_APPLICANTS_FAILURE";
export const GET_LOAN_APPLICANTS_SUCCESS = "GET_LOAN_APPLICANTS_SUCCESS";