export const SAVE_PERSONAL_DATA = "SAVE_PERSONAL_DATA";
export const SAVE_ADDRESS_DATA = "SAVE_ADDRESS_DATA"
export const SAVE_FINANCE_PRODUCT_DETAILS = "SAVE_FINANCE_PRODUCT_DETAILS"
export const SAVE_CHEQUE_DETAILS = "SAVE_CHEQUE_DETAILS"
export const SAVE_GUARANTOR_DETAILS = "SAVE_GUARANTOR_DETAILS"